import { 
  User, 
  Organization, 
  Project, 
  Deployment, 
  Repository, 
  Metrics,
  Notification,
  APIKey,
  Domain
} from './types'

export const mockUser: User = {
  id: 'user_1',
  email: 'developer@example.com',
  username: 'developer',
  avatar: undefined,
  createdAt: '2024-01-15T10:00:00Z',
}

export const mockOrganizations: Organization[] = [
  {
    id: 'org_1',
    name: 'Personal',
    slug: 'personal',
    plan: 'pro',
  },
  {
    id: 'org_2',
    name: 'Acme Corp',
    slug: 'acme-corp',
    plan: 'enterprise',
  },
  {
    id: 'org_3',
    name: 'Startup Inc',
    slug: 'startup-inc',
    plan: 'free',
  },
]

export const mockProjects: Project[] = [
  {
    id: 'proj_1',
    name: 'marketing-site',
    slug: 'marketing-site',
    framework: 'nextjs',
    domain: 'marketing.nexuscloud.app',
    status: 'ready',
    lastDeployment: '2 hours ago',
    organizationId: 'org_1',
    createdAt: '2024-01-20T10:00:00Z',
    description: 'Company marketing website',
    repository: 'acme/marketing-site',
    branch: 'main',
  },
  {
    id: 'proj_2',
    name: 'dashboard-app',
    slug: 'dashboard-app',
    framework: 'react',
    domain: 'dashboard.nexuscloud.app',
    status: 'building',
    lastDeployment: '5 minutes ago',
    organizationId: 'org_1',
    createdAt: '2024-02-10T10:00:00Z',
    description: 'Internal dashboard application',
    repository: 'acme/dashboard',
    branch: 'main',
  },
  {
    id: 'proj_3',
    name: 'api-gateway',
    slug: 'api-gateway',
    framework: 'nodejs',
    domain: 'api.nexuscloud.app',
    status: 'ready',
    lastDeployment: '1 day ago',
    organizationId: 'org_2',
    createdAt: '2024-01-25T10:00:00Z',
    description: 'API Gateway service',
    repository: 'acme/api-gateway',
    branch: 'production',
  },
  {
    id: 'proj_4',
    name: 'mobile-backend',
    slug: 'mobile-backend',
    framework: 'express',
    domain: 'mobile-api.nexuscloud.app',
    status: 'error',
    lastDeployment: '3 hours ago',
    organizationId: 'org_2',
    createdAt: '2024-02-05T10:00:00Z',
    description: 'Mobile app backend services',
    repository: 'acme/mobile-backend',
    branch: 'main',
  },
  {
    id: 'proj_5',
    name: 'docs-site',
    slug: 'docs-site',
    framework: 'nextjs',
    domain: 'docs.nexuscloud.app',
    status: 'ready',
    lastDeployment: '6 hours ago',
    organizationId: 'org_1',
    createdAt: '2024-02-15T10:00:00Z',
    description: 'Documentation website',
    repository: 'acme/docs',
    branch: 'main',
  },
  {
    id: 'proj_6',
    name: 'analytics-service',
    slug: 'analytics-service',
    framework: 'python',
    domain: 'analytics.nexuscloud.app',
    status: 'ready',
    lastDeployment: '12 hours ago',
    organizationId: 'org_3',
    createdAt: '2024-02-20T10:00:00Z',
    description: 'Analytics and reporting service',
    repository: 'startup/analytics',
    branch: 'main',
  },
]

export const mockDeployments: Deployment[] = [
  {
    id: 'dep_1',
    projectId: 'proj_1',
    projectName: 'marketing-site',
    commit: 'a1b2c3d',
    commitMessage: 'Update hero section copy',
    branch: 'main',
    status: 'ready',
    duration: 45,
    createdAt: '2024-03-15T14:30:00Z',
    url: 'https://marketing-a1b2c3d.nexuscloud.app',
  },
  {
    id: 'dep_2',
    projectId: 'proj_2',
    projectName: 'dashboard-app',
    commit: 'e4f5g6h',
    commitMessage: 'Add new chart components',
    branch: 'main',
    status: 'building',
    duration: 0,
    createdAt: '2024-03-15T14:25:00Z',
  },
  {
    id: 'dep_3',
    projectId: 'proj_3',
    projectName: 'api-gateway',
    commit: 'i7j8k9l',
    commitMessage: 'Optimize database queries',
    branch: 'production',
    status: 'ready',
    duration: 62,
    createdAt: '2024-03-14T10:00:00Z',
    url: 'https://api-i7j8k9l.nexuscloud.app',
  },
  {
    id: 'dep_4',
    projectId: 'proj_4',
    projectName: 'mobile-backend',
    commit: 'm1n2o3p',
    commitMessage: 'Fix authentication middleware',
    branch: 'main',
    status: 'error',
    duration: 23,
    createdAt: '2024-03-15T11:00:00Z',
    logs: [
      '> Building application...',
      '> Installing dependencies...',
      '> npm install',
      '> Error: Cannot find module "express-validator"',
      '> Build failed with exit code 1',
    ],
  },
  {
    id: 'dep_5',
    projectId: 'proj_5',
    projectName: 'docs-site',
    commit: 'q4r5s6t',
    commitMessage: 'Add API reference documentation',
    branch: 'main',
    status: 'ready',
    duration: 38,
    createdAt: '2024-03-15T08:00:00Z',
    url: 'https://docs-q4r5s6t.nexuscloud.app',
  },
  {
    id: 'dep_6',
    projectId: 'proj_1',
    projectName: 'marketing-site',
    commit: 'u7v8w9x',
    commitMessage: 'Update pricing page',
    branch: 'main',
    status: 'ready',
    duration: 42,
    createdAt: '2024-03-14T16:00:00Z',
    url: 'https://marketing-u7v8w9x.nexuscloud.app',
  },
  {
    id: 'dep_7',
    projectId: 'proj_6',
    projectName: 'analytics-service',
    commit: 'y1z2a3b',
    commitMessage: 'Add new metrics endpoint',
    branch: 'main',
    status: 'ready',
    duration: 89,
    createdAt: '2024-03-15T06:00:00Z',
    url: 'https://analytics-y1z2a3b.nexuscloud.app',
  },
]

export const mockRepositories: Repository[] = [
  {
    id: 'repo_1',
    name: 'marketing-site',
    fullName: 'acme/marketing-site',
    owner: 'acme',
    private: false,
    language: 'TypeScript',
    updatedAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'repo_2',
    name: 'dashboard',
    fullName: 'acme/dashboard',
    owner: 'acme',
    private: true,
    language: 'TypeScript',
    updatedAt: '2024-03-14T15:00:00Z',
  },
  {
    id: 'repo_3',
    name: 'api-gateway',
    fullName: 'acme/api-gateway',
    owner: 'acme',
    private: true,
    language: 'JavaScript',
    updatedAt: '2024-03-13T12:00:00Z',
  },
  {
    id: 'repo_4',
    name: 'mobile-backend',
    fullName: 'acme/mobile-backend',
    owner: 'acme',
    private: true,
    language: 'JavaScript',
    updatedAt: '2024-03-12T09:00:00Z',
  },
  {
    id: 'repo_5',
    name: 'docs',
    fullName: 'acme/docs',
    owner: 'acme',
    private: false,
    language: 'MDX',
    updatedAt: '2024-03-11T14:00:00Z',
  },
  {
    id: 'repo_6',
    name: 'design-system',
    fullName: 'acme/design-system',
    owner: 'acme',
    private: false,
    language: 'TypeScript',
    updatedAt: '2024-03-10T11:00:00Z',
  },
]

export const mockMetrics: Metrics = {
  totalProjects: 6,
  totalDeployments: 142,
  totalDomains: 8,
  bandwidth: '1.2 TB',
  requests: '2.4M',
  buildMinutes: 847,
}

export const mockNotifications: Notification[] = [
  {
    id: 'notif_1',
    title: 'Deployment Successful',
    message: 'marketing-site deployed to production',
    type: 'success',
    read: false,
    createdAt: '2024-03-15T14:30:00Z',
  },
  {
    id: 'notif_2',
    title: 'Build Failed',
    message: 'mobile-backend deployment failed',
    type: 'error',
    read: false,
    createdAt: '2024-03-15T11:00:00Z',
  },
  {
    id: 'notif_3',
    title: 'Domain Verified',
    message: 'docs.nexuscloud.app is now active',
    type: 'info',
    read: true,
    createdAt: '2024-03-14T09:00:00Z',
  },
]

export const mockAPIKeys: APIKey[] = [
  {
    id: 'key_1',
    name: 'Production API Key',
    key: 'nxs_prod_a1b2c3d4e5f6g7h8i9j0',
    lastUsed: '2024-03-15T10:00:00Z',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'key_2',
    name: 'Development API Key',
    key: 'nxs_dev_k1l2m3n4o5p6q7r8s9t0',
    lastUsed: '2024-03-14T16:00:00Z',
    createdAt: '2024-02-05T10:00:00Z',
  },
]

export const mockDomains: Domain[] = [
  {
    id: 'dom_1',
    domain: 'marketing.nexuscloud.app',
    projectId: 'proj_1',
    status: 'active',
    ssl: true,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'dom_2',
    domain: 'www.acme-corp.com',
    projectId: 'proj_1',
    status: 'active',
    ssl: true,
    createdAt: '2024-01-25T10:00:00Z',
  },
  {
    id: 'dom_3',
    domain: 'dashboard.nexuscloud.app',
    projectId: 'proj_2',
    status: 'active',
    ssl: true,
    createdAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'dom_4',
    domain: 'api.nexuscloud.app',
    projectId: 'proj_3',
    status: 'active',
    ssl: true,
    createdAt: '2024-01-25T10:00:00Z',
  },
]

export const frameworkOptions = [
  { value: 'nextjs', label: 'Next.js', icon: 'nextjs' },
  { value: 'react', label: 'React', icon: 'react' },
  { value: 'vue', label: 'Vue.js', icon: 'vue' },
  { value: 'nuxt', label: 'Nuxt', icon: 'nuxt' },
  { value: 'svelte', label: 'Svelte', icon: 'svelte' },
  { value: 'nodejs', label: 'Node.js', icon: 'nodejs' },
  { value: 'express', label: 'Express', icon: 'express' },
  { value: 'nestjs', label: 'NestJS', icon: 'nestjs' },
  { value: 'python', label: 'Python', icon: 'python' },
  { value: 'django', label: 'Django', icon: 'django' },
  { value: 'flask', label: 'Flask', icon: 'flask' },
  { value: 'go', label: 'Go', icon: 'go' },
  { value: 'docker', label: 'Docker', icon: 'docker' },
  { value: 'static', label: 'Static', icon: 'static' },
] as const
